CREATE TABLE new_entity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   new_entity_id BIGINT,
   CONSTRAINT pk_new_entity PRIMARY KEY (id)
);

CREATE TABLE new_entity_das (
  owner_id BIGINT NOT NULL,
   da UNKNOWN__JAVA.UTIL.SET<BYTE[]>
);

ALTER TABLE new_entity ADD CONSTRAINT FK_NEW_ENTITY_ON_NEW_ENTITY FOREIGN KEY (new_entity_id) REFERENCES new_entity (id);

ALTER TABLE new_entity_das ADD CONSTRAINT fk_new_entity_das_on_new_entity FOREIGN KEY (owner_id) REFERENCES new_entity (id);